Add deploy script to create Omeka database if it doesn't exist using the omeka20.sql backup

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -3,3 +3,34 @@
 # build hook has been run but before the application has been started back
 # up again.  This script gets executed directly, so it could be python, php,
 # ruby, etc.
+
+set -e
+
+if [ -z $OPENSHIFT_MYSQL_DB_HOST ]
+then
+    echo 1>&2
+    echo "Could not find mysql database.  Please run:" 1>&2
+    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
+    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+    echo 1>&2
+    exit 5
+fi
+
+# Confirm the database exists, if not create it
+if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -e "show tables;" omeka20 > /dev/null 2>&1
+then
+    echo
+    echo "Database not found!  Creating and importing"
+    echo
+    /usr/bin/mysqladmin -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" create "omeka20"
+    /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" omeka20 < "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/omeka20.sql"
+    echo
+    echo "done."
+    echo "==================================================="
+    echo "  Omeka 2.0 Admin login: Administrator"
+    echo "  Omeka 2.0 Admin password: OpenShiftAdmin"
+    echo "  Don't forget to change your Omeka admin password!"
+    echo "==================================================="
+else
+    echo "Database found, skipping build"
+fi
